### ISSUE TITLE
Driver discovery update tracking issue

### ISSUE THREAD

**Issue by danielballan** [intake/intake#392]
This issue is to track adding `entry_points` to packages that ship intake drivers.

Checked off when _merged_. (Should we check off when _released_ instead?)

## Projects under the intake org

- [x] https://github.com/intake/intake-xarray/pull/43
- [ ] https://github.com/intake/intake-parquet/pull/12
- [ ] https://github.com/intake/intake-astro/pull/6
- [ ] https://github.com/intake/intake-splunk/pull/5
- [ ] intake-sroka
- [ ] intake-spark
- [ ] intake-avro
- [ ] intake-elasticsearch
- [ ] intake-sql
- [ ] intake-accumulo
- [ ] intake-odbc
- [ ] intake-postgres
- [ ] intake-pcap
- [ ] intake-solr
- [ ] intake-mongo
- [ ] intake-hbase
- [ ] intake-netflow

## Projects not under the intake organization

- [ ] https://github.com/bluesky/intake-bluesky/pull/62
TODO add more...

**Comment by martindurant** [comment]
You have been busy! :)

This issue is a good idea, so we can ping external repo owners.

**Comment by danielballan** [comment]
I set this work down for a bit to see how the new discovery mechanism would hold up "in the wild." Six months on, it seems to be going fine, so I intend to resume updating more intake projects this week.

**Comment by martindurant** [comment]
Hurray! :)

**Comment by danielballan** [comment]
There are now PRs for every one of the plugins listed in the [Plugin Directory](https://intake.readthedocs.io/en/latest/plugin-directory.html, including external repos.

**Comment by danielballan** [comment]
The 5 yet-unmerged PRs are either:

* in the `informatics-labs` org, passing CI and awaiting review
* failing CI in a way that looks like bit rot on the `master` branch not an issue with the PR

All the failures related to `anaconda upload ...` have been resolved.

**Comment by martindurant** [comment]
e.g., pysolr was never released beyond py36, there may be nothing we can do about that.

**Comment by martindurant** [comment]
- [ ] intake-stac (now at https://github.com/pangeo-data/intake-stac )
- [ ] intake-dal ( https://github.com/zillow/intake-dal )
- [ ] intake-nested-yaml-catalog ( https://github.com/zillow/intake-nested-yaml-catalog )
- [ ] intake-hive ( https://github.com/zillow/intake-hive )

**Comment by martindurant** [comment]
^ cc @talebzeghmi , I think your packages all comply?
